* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qmap_seg_SegmenterJni */

#ifndef _Included_qmap_seg_SegmenterJni
#define _Included_qmap_seg_SegmenterJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qmap_seg_SegmenterJni
 * Method:    segment
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_qmap_seg_SegmenterJni_segment
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
